name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Cache SonarQube Scanner
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.java') }}
          restore-keys: |
            ${{ runner.os }}-sonar-

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          sonar-project-key: ${{ secrets.SONAR_PROJECT_KEY }}
          sonar-host-url: 'https://0bae-2a09-bac1-3480-18-00-da-8e.ngrok-free.app' # URL Ngrok
          sonar-login: ${{ secrets.SONAR_TOKEN }}
